include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    # strict-casts: true
    strict-raw-types: true
  errors:
    # always_declare_return_types: warning
    # avoid_init_to_null: ignore
    avoid_function_literals_in_foreach_calls: ignore
    # avoid_unnecessary_containers: ignore
    # await_only_futures: ignore
    avoid_print: ignore
    camel_case_types: ignore
    curly_braces_in_flow_control_structures: ignore
    dead_code: ignore
    # deprecated_member_use: ignore
    # depend_on_referenced_packages: ignore
    # duplicate_import: ignore
    # empty_catches: ignore
    # empty_statements: ignore
    file_names: ignore
    library_prefixes: ignore
    library_private_types_in_public_api: ignore
    # missing_return: ignore
    must_be_immutable: ignore
    # no_leading_underscores_for_local_identifiers: ignore
    non_constant_identifier_names: ignore
    # prefer_conditional_assignment: ignore
    # prefer_contains: ignore
    # prefer_const_literals_to_create_immutables: ignore
    # prefer_const_constructors: ignore
    # prefer_const_constructors_in_immutables: ignore
    # prefer_final_fields: ignore
    # prefer_function_declarations_over_variables: ignore
    # prefer_interpolation_to_compose_strings: ignore
    # prefer_initializing_formals: ignore
    # prefer_is_empty: ignore
    # prefer_is_not_operator: ignore
    # prefer_single_quotes: ignore
    # prefer_typing_uninitialized_variables: ignore
    # unawaited_futures: ignore
    # unnecessary_string_interpolations: ignore
    use_build_context_synchronously: ignore
    # sized_box_for_whitespace: ignore
    # sort_child_properties_last: ignore
    prefer_final_fields: error
    prefer_typing_uninitialized_variables: error
    todo: ignore
    unnecessary_null_comparison: ignore
    # # unawaited_futures: warning
    dead_null_aware_expression: ignore
    # unnecessary_new: ignore
    # unnecessary_this: ignore
    # unrelated_type_equality_checks: error
    # unused_catch_clause: ignore
    unused_element: ignore
    unused_field: ignore
    # unused_import: ignore
    unused_local_variable: ignore
    # use_key_in_widget_constructors: ignore


linter:
  rules:
    - unawaited_futures
    - avoid_void_async
    - file_names
    - avoid_function_literals_in_foreach_calls
    - always_declare_return_types
    - directives_ordering
    # - omit_local_variable_types
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_relative_imports
    - sort_constructors_first
    # - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unnecessary_lambdas
    - unnecessary_parenthesis
