name: flutter_ebs3
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  sqflite: ^2.0.3
  # parse_server_sdk: ^2.0.1
  # https://firebase.flutter.dev/docs/overview
  # 0.5.3

  #firebase_auth: ^1.2.0
  firebase_auth: ^5.3.1

  #firebase_core: ^1.2.0
  firebase_core: ^3.6.0

  #cloud_firestore: ^2.2.0
  cloud_firestore: ^5.4.3

  # flutter_js: ^0.2.2+0
  validators: ^3.0.0
  # pdf: ^1.13.0
  # printing: ^3.7.2
  pdf: ^3.8.4
  printing: ^5.2.1
  path_provider: ^2.0.9
  path:
  open_file: ^3.2.1
  file: ^7.0.0
  html: ^0.15.0
  #image: ^3.0.2
  image: ^4.0.0
  http: ^0.13.6
  hand_signature: ^3.0.3
  crypto:
  platform: ^3.1.0
  shared_preferences:
  provider: ^6.0.3
  firebase_storage: ^12.3.2
  #sentry_flutter: ^8.14.1
  sentry_flutter: 8.13.3
  firebase_analytics: ^11.4.5

  # firebase_analytics:
  image_picker: ^1.1.2
  file_selector: ^1.0.3
  file_selector_web: ^0.9.4+2
  # image_picker_for_web: ^0.1.0+2
  mime_type: ^1.0.0
  #media_info: ^0.10.0
  url_launcher: ^6.0.4
  #screenshot: ^0.3.0
  pdf_crypto:
    hosted:
      name: pdf_crypto
      #url: https://ebs:tL3E1Sa4Y5p6t@pub.nfet.net
      url: https://pub.nfet.net/tL3E1Sa4Y5p6t
  flutter_email_sender: ^6.0.3
  parse_server_sdk: ^6.4.0
  #codemirror:
  translator: ^0.1.7
  flutter_markdown: ^0.7.3+2
  logging: ^1.0.2
  # image_downloader: ^0.31.0
  image_size_getter: ^2.1.1
  flutter_exif_rotation: ^0.5.1
  logger: ^2.4.0
  # flutter_sms: ^2.3.3
  flutter_image_compress: ^2.3.0
  # firebase_crashlytics: ^4.1.3
  # charts_flutter: ^0.12.0
  restart_app: ^1.1.0+1
  audioplayers: ^6.1.0
  #google_maps_flutter: ^2.2.2
  location: ^6.0.2
  #geocoding: ^2.0.5
  #geocoding_web:
  #  path: geocoding_web
  #google_maps_flutter_web: ^0.4.0+3
  code_editor: ^2.1.0
  exif: ^3.1.4
  csv: ^6.0.0
  image_downloader_web: ^2.0.2
  fleather: ^1.7.0
  parchment: ^1.7.0
  htmltopdfwidgets: ^1.0.3
  flutter_quill: ^10.8.2
  archive: ^3.4.9
  sendgrid_mailer: ^0.1.3
  clipboard: ^0.1.3
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  # super_drag_and_drop: ^0.3.0+2

  #flutter_ebquery:
  #  path: ../flutter_ebquery

  intl: any
  community_charts_flutter: ^1.0.4
  cron: ^0.6.1
  photo_manager: ^3.6.4
  file_picker: ^10.1.2
  pdfx: ^2.9.0
  internet_file: ^1.2.0
  device_info_plus: ^9.0.3
##  uuid: ^4.5.1 # add this to explicitly require the latest uuid

dependency_overrides:
  uuid: ^4.5.1

flutter_icons:
  android: ic_launcher
  ios: true
  image_path: assets/images/ebs_icon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/ebs_icon.png
  android: true
  ios: false
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: ^0.9.2
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.0.1
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
