// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoqsTfKnO1fuvVVCGvLZCbgYedKN2JgjQ',
    appId: '1:118532743817:web:008f4bbe10e2b53a285c58',
    messagingSenderId: '118532743817',
    projectId: 'ebs-inspector-2',
    authDomain: 'ebs-inspector-2.firebaseapp.com',
    databaseURL: 'https://ebs-inspector-2.firebaseio.com',
    storageBucket: 'ebs-inspector-2.appspot.com',
    measurementId: 'G-J45GVS6JNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsvDbR7Ddv3OX1MIL-RQjhP9LAR5tbLCc',
    appId: '1:118532743817:android:50231d59a3e508f9285c58',
    messagingSenderId: '118532743817',
    projectId: 'ebs-inspector-2',
    databaseURL: 'https://ebs-inspector-2.firebaseio.com',
    storageBucket: 'ebs-inspector-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADG_4YeYtN5zXQxqjhzwYBnBg57yeRDeI',
    appId: '1:118532743817:ios:13b094a7dfd82b7a285c58',
    messagingSenderId: '118532743817',
    projectId: 'ebs-inspector-2',
    databaseURL: 'https://ebs-inspector-2.firebaseio.com',
    storageBucket: 'ebs-inspector-2.appspot.com',
    iosClientId: '118532743817-s7de9k7h65f8sj2oupd45u15i705bn90.apps.googleusercontent.com',
    iosBundleId: 'ca.eBusinessSolutions.EBSInspector3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADG_4YeYtN5zXQxqjhzwYBnBg57yeRDeI',
    appId: '1:118532743817:ios:cdecae6be582904a285c58',
    messagingSenderId: '118532743817',
    projectId: 'ebs-inspector-2',
    databaseURL: 'https://ebs-inspector-2.firebaseio.com',
    storageBucket: 'ebs-inspector-2.appspot.com',
    iosBundleId: 'ca.eBusinessSolutions.flutterEbs3',
  );
}
