name: Dart CI

on:
  pull_request:
    branches: [master42]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Run analysis
        run: make analyze
      - name: Run tests
        run: make test
      - name: Verify that nothing changed
        run: test -z "$(git status --porcelain)"
